### ISSUE TITLE
Deploy backend service on ReCaS server

### ISSUE THREAD

**Issue by federico-code** [collab-uniba/qavmentor#13]

**Comment by federico-code** [comment]
Al momento non è possibile  effettuare richieste al server tramite https, i servizi di java e R non sono al momento attivi

**Comment by gigium** [comment]
Fare richiesta certificati a: http://ca.garr.it/

**Comment by federico-code** [comment]
aggiunta di analisi del sentiment e calcolo di bontà della domanda come servizi disponibili e accessibili dal back-end

**Comment by gigium** [comment]
Deploy completato e usabile con google chrome lanciato con flag  --args --ignore-certificate-errors.
Apro nuova issue #27 per l'aggiunta del certificato.
