### ISSUE TITLE
Set the R model as a service

### ISSUE THREAD

**Issue by lanubile** [collab-uniba/qavmentor#20]

**Comment by lanubile** [comment]
https://www.google.com/search?q=r+model+as+a+service&ie=utf-8&oe=utf-8&client=firefox-b

**Comment by nnovielli** [comment]
https://www.google.com/search?q=R+running+on+web+server&ie=utf-8&oe=utf-8&client=firefox-b-ab

**Comment by nnovielli** [comment]
https://stackoverflow.com/questions/9174114/how-to-set-up-an-r-based-service-on-a-web-page
http://rforge.net/FastRWeb/
