### ISSUE TITLE
Add code coverage tool

### ISSUE THREAD

**Issue by federico-code** [collab-uniba/qavmentor#21]

**Comment by bateman** [comment]
Direi codecov.io, coveralls non ci ha soddisfatti molto.
E' gratis per tutti i progetti aperti.

**Comment by federico-code** [comment]
Abbiamo scelto codecov.io come strumento di misura della copertura dei test del codice

**Comment by gigium** [comment]
Risolto problema relativo al coverage degli script di test cambiando la struttura della directory.
In particolare abbiamo racchiuso tutti gli script da testare in un'unica cartella(src).
